package com.civora.app.core.model

data class UserProfile(
    val id: String,
    val nationalId: String,
    val fullNameEn: String,
    val fullNameAr: String,
    val dateOfBirth: String = "1988/02/03",
    val dateOfBirthAr: String = "١٩٨٨/٠٢/٠٣",
    val dateOfBirthHijri: String = "1408/10/18",
    val nationality: String = "Bangladesh",
    val nationalityAr: String = "بنجلاديش",
    val placeOfBirthEn: String = "Bangladesh",
    val placeOfBirthAr: String = "بنجلاديش",
    val religionEn: String = "Islam",
    val religionAr: String = "الاسلام",
    val professionEn: String = "Laundry Worker",
    val professionAr: String = "عامل غسيل ملابس",
    val sponsorId: String = "7034884309",
    val sponsorNameEn: String = "Durrat Najah Laundry",
    val sponsorName: String = "مغاسل درر نجاح للملابس",
    val issuePlaceEn: String = "Elm Information Security",
    val issuePlace: String = "شركة العلم لامن المعلومات",
    val workPlaceAr: String = "منطقة الرياض",
    val expiryDateEn: String = "2026/10/08",
    val expiryDateAr: String = "٢٠٢٦/١٠/٠٨",
    val versionNumber: String = "٢",
    val expiryDateDigits: String = "081026",
    val issueDateDigits: String = "070926",
    val verificationLevel: VerificationLevel = VerificationLevel.TIER_3_VERIFIED,
    val digitalIdActive: Boolean = true,
    val totalDocuments: Int = 4,
    val activeRequestsCount: Int = 2,
    val unreadNotificationsCount: Int = 3,
    val birthCity: String = "-",
    val birthCountry: String = "Bangladesh",
    val maritalStatus: String = "SINGLE",
    val sponsorshipTransfers: String = "2",
    val workPermit: String = "-",
    val biometricsCollected: String = "Yes",
    val travelStatus: String = "Inside Kingdom",
    val establishmentStatus: String = "Active (Green)",
    val insuranceCompany: String = "Bupa Arabia",
    val insurancePolicyNo: String = "POL-9842144",
    val insuranceStatus: String = "Valid & Active",
    val insuranceExpiry: String = "14/04/2026",
    val hajjEligibility: String = "Not Eligible / Not Performed",
    val lastHajjYear: String = "-"
)

enum class VerificationLevel(val label: String) {
    BASIC("Level 1 Basic"),
    VERIFIED("Level 2 Verified"),
    TIER_3_VERIFIED("Tier 3 Fully Verified")
}
