import { UserProfile, DigitalDocument } from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr_992140',
    nationalId: '2495685261',
    appPassword: 'Civora2026!',
    accountStatus: 'ACTIVE',
    fullNameEn: 'MD ABDUL HALIM MEIA',
    fullNameAr: 'مد عبد ال حليم مياه',
    dateOfBirth: '1988/02/03',
    dateOfBirthAr: '١٩٨٨/٠٢/٠٣',
    dateOfBirthHijri: '1408/10/18',
    nationality: 'Bangladesh',
    nationalityAr: 'بنجلاديش',
    placeOfBirthEn: 'Bangladesh',
    placeOfBirthAr: 'بنجلاديش',
    religionEn: 'Islam',
    religionAr: 'الاسلام',
    professionEn: 'Laundry Worker',
    professionAr: 'عامل غسيل ملابس',
    sponsorId: '7034884309',
    sponsorNameEn: 'Durrat Najah Laundry',
    sponsorName: 'مؤسسة درر نجاح للملابس',
    issuePlaceEn: 'Elm Information Security',
    issuePlace: 'شركة العلم لامن المعلومات',
    workPlaceAr: 'منطقة الرياض',
    expiryDateEn: '2026/10/08',
    expiryDateAr: '٢٠٢٦/١٠/٠٨',
    versionNumber: '٢',
    expiryDateDigits: '081026',
    issueDateDigits: '070926',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    verificationLevel: 'TIER_3_VERIFIED',
    digitalIdActive: true,
    totalDocuments: 4,
    activeRequestsCount: 2,
    unreadNotificationsCount: 3,
    createdAt: '2024-01-15',
    updatedAt: '2026-09-15'
  },
  {
    id: 'usr_109844',
    nationalId: '1098442190',
    appPassword: 'Civora2026!',
    accountStatus: 'ACTIVE',
    fullNameEn: 'TARIQ ABDULAZIZ AL-MANSOOR',
    fullNameAr: 'طارق عبدالعزيز المنصور',
    dateOfBirth: '1992/05/14',
    dateOfBirthAr: '١٩٩٢/٠٥/١٤',
    dateOfBirthHijri: '1412/11/11',
    nationality: 'Saudi Arabia',
    nationalityAr: 'المملكة العربية السعودية',
    placeOfBirthEn: 'Riyadh',
    placeOfBirthAr: 'الرياض',
    religionEn: 'Islam',
    religionAr: 'الاسلام',
    professionEn: 'Senior Systems Architect',
    professionAr: 'مهندس نظم رئيسي',
    sponsorId: '7001928410',
    sponsorNameEn: 'Ministry of Communications & IT',
    sponsorName: 'وزارة الاتصالات وتقنية المعلومات',
    issuePlaceEn: 'Civil Affairs Riyadh',
    issuePlace: 'الأحوال المدنية - الرياض',
    workPlaceAr: 'منطقة الرياض',
    expiryDateEn: '2030/01/20',
    expiryDateAr: '٢٠٣٠/٠١/٢٠',
    versionNumber: '١',
    expiryDateDigits: '200130',
    issueDateDigits: '150120',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    verificationLevel: 'TIER_3_VERIFIED',
    digitalIdActive: true,
    totalDocuments: 3,
    activeRequestsCount: 1,
    unreadNotificationsCount: 0,
    createdAt: '2023-08-10',
    updatedAt: '2026-09-10'
  },
  {
    id: 'usr_239104',
    nationalId: '2391049921',
    appPassword: 'Civora2026!',
    accountStatus: 'ACTIVE',
    fullNameEn: 'FATIMA NOOR AHMED',
    fullNameAr: 'فاطمة نور أحمد',
    dateOfBirth: '1995/11/22',
    dateOfBirthAr: '١٩٩٥/١١/٢٢',
    dateOfBirthHijri: '1416/06/29',
    nationality: 'Egypt',
    nationalityAr: 'مصر',
    placeOfBirthEn: 'Cairo',
    placeOfBirthAr: 'القاهرة',
    religionEn: 'Islam',
    religionAr: 'الاسلام',
    professionEn: 'Registered Pharmacist',
    professionAr: 'صيدلي قانوني',
    sponsorId: '7019823412',
    sponsorNameEn: 'Nahdi Medical Company',
    sponsorName: 'شركة النهدي الطبية',
    issuePlaceEn: 'Jeddah Passport Office',
    issuePlace: 'جوازات محافظة جدة',
    workPlaceAr: 'منطقة مكة المكرمة',
    expiryDateEn: '2025/12/15',
    expiryDateAr: '٢٠٢٥/١٢/١٥',
    versionNumber: '٣',
    expiryDateDigits: '151225',
    issueDateDigits: '101224',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    verificationLevel: 'TIER_3_VERIFIED',
    digitalIdActive: true,
    totalDocuments: 2,
    activeRequestsCount: 0,
    unreadNotificationsCount: 1,
    createdAt: '2024-03-01',
    updatedAt: '2026-08-20'
  }
];

export const INITIAL_DOCUMENTS: DigitalDocument[] = [
  {
    id: 'doc_2495685261',
    userId: 'usr_992140',
    type: 'RESIDENCE_PERMIT',
    title: 'Resident Identity (Muqeem)',
    titleAr: 'هوية مقيم',
    subtitle: 'Ministry of Interior - General Directorate of Passports',
    documentNumber: '2495685261',
    issueDate: '1448/03/24 H',
    expiryDate: '1448/03/24 H (2026/10/08 G)',
    status: 'ACTIVE',
    issuer: 'General Directorate of Passports',
    qrCodePayload: 'https://absher.sa/verify/2495685261?version=2&expiry=20261008',
    details: {
      'Full Name': 'MD ABDUL HALIM MEIA',
      'Arabic Name': 'مد عبد ال حليم مياه',
      'Profession': 'عامل غسيل ملابس',
      'Employer': 'مؤسسة درر نجاح للملابس'
    }
  },
  {
    id: 'doc_1098442190',
    userId: 'usr_109844',
    type: 'NATIONAL_ID',
    title: 'National Identity Card',
    titleAr: 'الهوية الوطنية',
    subtitle: 'Ministry of Interior - Civil Affairs',
    documentNumber: '1098442190',
    issueDate: '1441/06/10 H',
    expiryDate: '1451/06/10 H',
    status: 'ACTIVE',
    issuer: 'Civil Affairs Agency',
    qrCodePayload: 'https://absher.sa/verify/1098442190?version=1',
    details: {
      'Full Name': 'Tariq Abdulaziz Al-Mansoor',
      'Arabic Name': 'طارق عبدالعزيز المنصور',
      'Blood Group': 'O+'
    }
  }
];
